global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: "scalebee"
    scrape_interval: 3s
    scrape_timeout: 2s
    static_configs:
      - targets: ["scalebee:9090"]
