global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: "scalebee"
    scrape_interval: 7s
    static_configs:
      - targets: ["scalebee:9090"]
